DB_HOST = "localhost"
DB_PORT = 3306
DB_NAME = "dailyarxiv"
DB_USER = "root"
DB_PASSWORD = "kashmir0661"
REDIS_HOST = "localhost"
REDIS_PORT = 6379
DIFY_API_URL = "https://api.dify.ai/v1/completion-messages"
DIFY_API_KEY = "app-8HazUVj4AStktGTNwLTPudCZ"
DIFY_USER = "root"
max_result = 1
issues_result = 15
keywords = [ "Efficient Diffusion Models", "Inference Compression", "Fast Inference",]
